config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts do
    resources :comments, only: [:create]
  end
  root to: 'blog_posts#index'
  # Query exercise with the comments on the index
  resources :comments, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  # GET /blog_posts or /blog_posts.json
  def index
    @pagy, @blog_posts = pagy(BlogPost.all)
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: "Blog post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Blog post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog_post, only: :create

  def index
    if params[:query].present?
      # Posgresql's version
      # sql_query = " \
      #   comments.body @@ :query \
      #   OR blog_posts.title @@ :query \
      #   OR blog_posts.body @@ :query \
      # "
      # SQlite's version
      sql_query = <<~SQL
        comments.body LIKE :query
        OR blog_posts.title LIKE :query
        OR blog_posts.body LIKE :query
      SQL
      @comments = Comment.joins(:blog_post).where(sql_query, query: "%#{params[:query]}%")
    end
  end

  def create
    comment = Comment.new(comment_params)
    comment.blog_post = @blog_post
    if comment.save
      # Instead of redirecting like we normally would, we render a partial for our Stimulus controller to handle
      # Note that we're just rendering HTML here, no need to render jbuilders or js partials
      # render partial: 'show', locals: { comment: comment }, status: :ok
      redirect_to @blog_post
    else
      render partial: 'form', locals: { comment: comment }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post) do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Posts</h1>

<%= link_to "Dangerous zone", "#", data: { confirm: 'It was a joke!' } %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_posts.each do |blog_post| %>
      <tr>
        <td><%= blog_post.title %></td>
        <td><%= blog_post.body %></td>
        <td><%= link_to 'Show', blog_post %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
        <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Post', new_blog_post_path %>
<%== pagy_nav(@pagy) %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="comments" data-controller="comments">
  <h2>Title</h2>
  <div>
    <%= @blog_post.title %>
  </div>
  <h2>Body</h2>
  <div>
    <%= @blog_post.body %>
  </div>
  <h2>Comments</h2>
  <div data-target="comments.commentList">
    <% @blog_post.comments.each do |comment| %>
      <%= render partial: "comments/show", locals: { comment: comment } %>
    <% end %>
  </div>
  <div>
    <%= render partial: "comments/form", locals: { blog_post_id: @blog_post.id } %>
  </div>
</div>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/comments/_form.html.erb
<%= form_with model: Comment.new, url: blog_post_comments_path(blog_post_id: blog_post_id), data: { action: "ajax:success->comments#createSuccess" } do |form| %>
  <div>
    <%= form.text_field :body, data: { target: "comments.commentBody" }, placeholder: true %>
  </div>
  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<div>
  <%= comment.body %>
</div>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= form_tag comments_path, method: :get do %>
  <%= text_field_tag :query, params[:query], placeholder: "Find a comment" %>
  <%= submit_tag "Search" %>
<% end %>

<% if @comments %>
  <table>
    <thead>
      <tr>
        <th>Body</th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pagytest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>